name: Main Terraform Trigger

on:
  pull_request:
    branches:
      - main

jobs:
  static-analysis:
    name: Análisis Estático
    uses: ./.github/workflows/terraform.yml
    with:
      path: .

  security-analysis:
    name: Análisis de Seguridad
    needs: static-analysis
    uses: ./.github/workflows/checkov.yml
    with:
      path: .

  terraform-validation:
    name: Validación Terraform
    needs: security-analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: Terraform Init y Validate
        run: |
          terraform init -backend=false
          terraform validate

  opa-policy:
    name: Validación OPA
    needs: terraform-validation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Instalar OPA
        run: |
          curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64_static
          chmod +x opa
          sudo mv opa /usr/local/bin/

      - name: Generar plan de Terraform
        run: |
          terraform init
          terraform plan -out=tfplan
          terraform show -json tfplan > tfplan.json

      - name: Evaluar políticas
        run: |
          opa eval --fail-defined --format pretty \
          --data policy/security.rego \
          --input tfplan.json \
          "data.terraform.security.deny"
