name: Terraform Lint

on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string

jobs:
  tflint:
    name: Ejecutar TFLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Instalar TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: Inicializar TFLint
        run: tflint --init

      - name: Ejecutar TFLint
        run: tflint --chdir=${{ inputs.path }} || true
